# -*- coding: utf-8 -*-
"""offer_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HxvfwqTSvfLnADiIFWm0CfbPmFLluZ0N
"""

def get_customized_offer_text(purchase_history_df):
    try:
        # Most frequent category
        top_category = purchase_history_df['category'].value_counts().idxmax()

        total_spent = purchase_history_df['total_amount'].sum()
        recent_spend = purchase_history_df.sort_values(by='purchase_date', ascending=False).head(3)['total_amount'].sum()

        # Offer rules
        if total_spent > 10000:
            return f"🌟 Premium Offer! 25% off on your next {top_category} purchase."
        elif recent_spend > 3000:
            return f"🎉 You're on a roll! Grab 15% off on {top_category} items this week."
        else:
            return f"👋 Special 10% welcome back offer on your favorite {top_category} products!"
    except Exception as e:
        return f"Could not generate offer: {e}"
