# -*- coding: utf-8 -*-
"""purchase_history_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAKN20ktogCp3leZxRsXnyUHIRh8ERuy
"""

# purchase_history_utils.py

import pandas as pd
import streamlit as st

def display_purchase_history(customer_id, known_faces_dir, data_path):
    try:
        df = pd.read_csv(data_path)

        customer_df = df[df['customer_id'] == int(customer_id)]

        if customer_df.empty:
            st.warning("No purchase history found for this customer.")
            return None

        # Cleaned and relevant columns
        selected_cols = ['purchase_date', 'product_name', 'item_count', 'total_amount', 'category']
        purchase_history = customer_df[selected_cols].copy()

        return purchase_history

    except FileNotFoundError:
        st.error("Data file not found.")
        return None
    except KeyError as e:
        st.error(f"Missing column in data: {e}")
        return None
    except Exception as e:
        st.error(f"Error displaying purchase history: {e}")
        return None
