# -*- coding: utf-8 -*-
"""tts_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxkgGDyy7gtpKQLY3AkBytHiQUpwaqe7
"""

import pyttsx3

def speak_text(text):
    engine = pyttsx3.init()
    engine.setProperty("rate", 150)
    engine.say(text)
    engine.runAndWait()